# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85d392710672f8523992016a2389151c3f79210f744af02f9070444b3c3818c858abc323e254fa4abf491cb3f60a0c3199bedcb98f141dd38b8923a9daab550

test:
  secret_key_base: 84c4f3e9fcbf8fbd551b7aa318c30ac81d8c4ae57c7ffbd5a422936ea94b603c8424b6c886471c5deef05fd75feea3dd176be79f375e69d67390ec41d80da7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
